### ISSUE TITLE
overlap is broken

### ISSUE THREAD

**Issue by jmicco** [SukkaW/fast-cidr-tools#1]
overlap is broken!  It doesnt matter how much faster it is!

x.overlap(['10.119.0.0/16'], ['10.119.10.6/24'])
true

x.overlap(['10.119.0.0/16'], ['172.20.250.229/31', '10.119.10.6/24'])
false

EXPECTED_RESULT: The second call to overlap should return true
ACTUAL_RESULT: The second call to overlap returns false

**Comment by SukkaW** [comment]
Fixed in https://github.com/SukkaW/fast-cidr-tools/commit/39c45a0a881dd2c778599f3f81e64add347f0b78 and the bugfix is included in version 0.3.1!
